### ISSUE TITLE
Created a google colab but the bot not working

### ISSUE THREAD

**Issue by ghost** [TwistedIO/GPT2-Telegram-Chatbot#2]
Hi,

Hope you are all well !

I created a google colab for testing your repository but it is not working.
https://colab.research.google.com/drive/16045Y6Rdzy4skvG0Yu925eQJFXRYQbK5?usp=sharing

Each time, I write a message it hangs on the reply "Computing..."

Do you know how to sort it out ? 
What s the version of the `python-telegram-bot` package that you are using ?

Cheers,
X

**Comment by saran-gangster** [comment]
google colab runs out of  memory prefer using a local runtime with high ram

**Comment by Existencce** [comment]
Its very slow, it can take 20 minutes if it doesn't have a strong cpu, ram space or uses a hard disk.

Check the console/htop/processor usage if it has that.

**Comment by Existencce** [comment]
The cuda GPU ran out of memory, I'm unsure how much memory google collab provides.

**Comment by xluxeq** [comment]
Try the 774M model, that's what I'm trying now.
Nice to see it mostly works on google collab though. My git clone pulls a older version though for some reason.

**Comment by xluxeq** [comment]
Works with 774M, also if you change your runtype to TPU I think 1558M works and it's faster. I also put a notebook in the git repo if you want to try that one.
